

# Setup
title:               Jon Norberg
tagline:             'Stockholm University'
description:         'Thoughts and ideas about Science'
url:                 http://zahachtah.github.com
baseurl:             /
paginate:            10

# About/contact
author:
  name:              Jon Norberg
  url:               https://zahachtah.github.com
  email:             jon.norberg@ecology.su.se

# Custom vars
version:             1.0.0
